# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20170901_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='absmag',
            field=models.FloatField(null=True, verbose_name='Absolute visual magnitude'),
        ),
        migrations.AlterField(
            model_name='star',
            name='dec',
            field=models.FloatField(null=True, verbose_name='Declination'),
        ),
        migrations.AlterField(
            model_name='star',
            name='dist',
            field=models.FloatField(null=True, verbose_name='Distance [pc]'),
        ),
        migrations.AlterField(
            model_name='star',
            name='mag',
            field=models.FloatField(null=True, verbose_name='Apparent visual magnitude'),
        ),
        migrations.AlterField(
            model_name='star',
            name='proper',
            field=models.SlugField(null=True, verbose_name='Common name'),
        ),
        migrations.AlterField(
            model_name='star',
            name='ra',
            field=models.FloatField(null=True, verbose_name='Right Ascension'),
        ),
        migrations.AlterField(
            model_name='star',
            name='spect',
            field=models.SlugField(null=True, verbose_name='Spectral type'),
        ),
    ]
